chore: simplify release github action
Signed-off-by: jmeridth <jmeridth@gmail.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -5,11 +5,9 @@ on:
     types: [completed]
     branches: [master, main]
 jobs:
-  version-file-changed:
+  release:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
-    outputs:
-      output: ${{ steps.version-file-changed.outputs }}
     steps:
       - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # (latest, untagged)
       - name: Version file changed
@@ -17,31 +15,10 @@ jobs:
         uses: tj-actions/changed-files@ea41e772876ff19a8d86e3315c52ceff3dae1941 # (latest, untagged)
         with:
           files: lib/blueprinter/version.rb
-  release:
-    runs-on: ubuntu-latest
-    needs: version-file-changed
-    if: ${{ needs.version-file-changed.output.any_changed == 'true' }}
-    steps:
-      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # (latest, untagged)
-      - name: Version file changed
-        id: version-file-changed
-        uses: tj-actions/changed-files@v37
-        with:
-          files: lib/blueprinter/version.rb
-      - name: Set up Ruby ${{ matrix.ruby }}
-        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
-        with:
-          ruby-version: ${{ matrix.ruby }}
-          bundler-cache: true
-      - name: Installing dependencies
-        run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
-      - name: Auth RubyGems
-        run: |
-          mkdir ~/.gem
-          install -m 0600 /dev/null ~/.gem/credentials
-          echo -e "---\n:rubygems_api_key: ${{ secrets.RUBY_GEMS_API_KEY }}" > ~/.gem/credentials
       - name: Release New Gem Version
-        run: |
-          GEM_VERSION=$(ruby -r "./lib/blueprinter/version.rb" -e "puts Blueprinter::VERSION")
-          echo "Attempting to release version '$GEM_VERSION' of Blueprinter..."
-          bundle exec rake release || true # Don't fail when deploy does not take place
+        if: ${{ steps.version-file-changed.outputs.any_changed == 'true' }}
+        uses: cadwallion/publish-rubygems-action@94a6f4cd5350581749c569b5001eecc864e3ad0b # (latest, untagged)
+        env:
+          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+          RUBYGEMS_API_KEY: ${{secrets.RUBY_GEMS_API_KEY}}
+          RELEASE_COMMAND: bundle exec rake release || true # Don't fail when deploy does not take place
